# Generated by Django 4.1.6 on 2023-02-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('VideoId', models.IntegerField(primary_key=True, serialize=False)),
                ('VideoTitle', models.CharField(max_length=50)),
                ('VideoDescription', models.CharField(max_length=200)),
                ('UploadTime', models.DateTimeField()),
                ('ThumbnailURL', models.URLField()),
            ],
        ),
    ]
