# Generated by Django 4.1.6 on 2023-02-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='VideoId',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
