# Generated by Django 4.1.6 on 2023-02-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchApp', '0003_alter_videos_videodescription_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='videos',
            index=models.Index(fields=['-UploadTime'], name='datetime_desc_idx'),
        ),
    ]
